Update README.md
shreybatra/Variable-Delivery-Cost-Finder pull request #3
Opened 2018-07-11 06:20 UTC by dreamviewer12

Add a missing info. for running the project.

2018-07-11 06:21 UTC, iamblizzard approved these changes

2018-07-11 06:22 UTC, iamblizzard reviewed
Need to be done.

2018-07-11 06:23 UTC, iamblizzard reviewed
Need to be done.

2018-08-23 14:31 UTC, shreybatra requested changes

2018-08-23 14:31 UTC, shreybatra commented on README.md
> +6. Run ani.py in a separate cmd to visualize(Note: It can only be executed on Python 2.x).
Not necessarily. ```can be executed on python 2.7 and above.```

2018-08-23 17:05 UTC, dreamviewer12 commented on README.md
> +6. Run ani.py in a separate cmd to visualize(Note: It can only be executed on Python 2.x).
Done @shreybatra

2018-08-24 13:22 UTC, shreybatra requested changes

2018-08-24 13:22 UTC, shreybatra commented on README.md
> +6. Run ani.py in a separate cmd to visualize(Note: It can only be executed on Python 2.x).
@dreamviewer12 can't see the changes. It's still the same.

2018-08-27 10:48 UTC, closed without merging